"""Data-driven non-combat quests. Add content here without changing the engine."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Step:
    action: str                 # talk or escort
    target: str
    objective: str
    result: str
    destination: str | None = None
    start_result: str | None = None


@dataclass(frozen=True)
class Quest:
    title: str
    giver: str
    offer: str
    steps: tuple[Step, ...]
    reward: int = 25
    requires: tuple[str, ...] = ()
    lead: str = ""


def T(target: str, objective: str, result: str) -> Step:
    return Step("talk", target, objective, result)


def E(target: str, destination: str, objective: str, result: str, start_result: str) -> Step:
    return Step("escort", target, objective, result, destination, start_result)


QUESTS: dict[str, Quest] = {
    "orientation": Quest("First Day in the Brewery", "training_coordinator",
        "“A brewery is a linked biochemical system, not just a row of tanks. For your first assignment, trace grain from malting through mash separation,” says the Training Coordinator.", (
        T("head_maltster", "Find and meet the Head Maltster.", "“Ah, you found me! Welcome to the maltings. Before I can judge this batch, I need to know whether the incoming grain was uniform. Find the Barley Inspector and ask what varied across the load,” says the Head Maltster."),
        T("barley_inspector", "Find the Barley Inspector and ask what varied across the incoming grain.", "“I sampled across the load, not just from the top. Kernel size and moisture were consistent enough for even steeping. Next, ask the Water Chemist what chemical environment those kernels and their enzymes will encounter,” says the Barley Inspector."),
        T("water_chemist", "Find the Water Chemist and ask how water affects mashing.", "“The grist and water react together to establish mash pH. Once that environment is understood, the grain still needs physical access—ask the Miller how the crush exposes endosperm without destroying the husks,” says the Water Chemist."),
        T("miller", "Find the Miller and ask how the crush exposes endosperm.", "“The rollers opened the endosperm but left useful husk pieces. The Head Brewer can now explain how temperature and pH turn that access into a particular balance of sugars and dextrins,” says the Miller."),
        T("head_brewer", "Find the Head Brewer and ask how mash conditions control fermentability.", "“Mash conditions shift which enzymes survive and which products accumulate. When conversion is complete, the Lauter Operator must separate that dissolved extract from the grain bed,” says the Head Brewer."),
        T("lauter_operator", "Find the Lauter Operator and ask how sweet wort is separated.", "“The husk-supported bed retains solids while sweet wort passes through. You have now traced grain from raw material to separated wort; take that process framework back to the Training Coordinator,” says the Lauter Operator."),
        T("training_coordinator", "Return to the Training Coordinator.", "“Good. You have followed the broad path from living grain to separated wort,” says the Training Coordinator. “Now return to the Head Maltster. One barley lot is germinating unevenly, and you will investigate each biochemical stage in detail before you come back to lautering.”")), 30,
        lead="The Training Coordinator has a first assignment tracing grain from malting through mash separation."),

    "malt_house": Quest("Wake the Sleeping Grain", "head_maltster",
        "“This lot is germinating unevenly. Trace the signal from hydrated embryo to starch-degrading enzymes,” says the Head Maltster.", (
        T("barley_inspector", "Ask the Barley Inspector about the grain.", "“The smaller kernels reached germination moisture first, while the larger ones lagged behind,” says the Barley Inspector. “Two-row barley is valued partly for uniform kernels because uniform starting material hydrates and modifies more consistently. Find Gibberellic Acid on the Germination Floor and trace what should happen after a kernel awakens.”"),
        T("gibberellic_acid", "Find the gibberellic-acid messenger.", "“I carry the embryo's germination signal, but I do not digest starch myself,” says Gibberellic Acid. “My message must reach living cells in the aleurone layer. Ask the Aleurone Cell which hydrolytic enzymes it produces in response.”"),
        T("aleurone_cell", "Ask the Aleurone Cell how it responds.", "“Gibberellin activates my synthesis and secretion of alpha-amylase, proteases, and other hydrolases,” says the Aleurone Cell. “Those enzymes open the matrix surrounding the stored reserves. Examine the Starch Granule in the endosperm to see whether modification progressed evenly.”"),
        T("starch_granule", "Check modification in the endosperm.", "“Cell walls and the protein matrix have opened around part of me, but other regions remain difficult to reach,” reports the Starch Granule. “That patchwork suggests uneven modification. Take Beta-Amylase's assay sample to the Head Maltster so enzyme activity can be separated from an accessibility problem.”"),
        E("beta_amylase", "head_maltster", "Escort Beta-Amylase's assay sample to the Head Maltster.", "The Head Maltster compares the assay with the uneven kernels. “Beta-Amylase is active in the sample, so the enzyme was not simply absent,” she says. “Variable hydration gave the kernels different biochemical starting times. More uniform grain selection and controlled wet steeps with oxygenating air rests should make the next lot modify more evenly.”", "“My assay cuvette contains active enzyme and a properly prepared starch substrate,” says Beta-Amylase. “Carry it carefully to the Head Maltster. Comparing this working control with the patchily modified grain will show whether the underlying problem was enzyme activity or uneven access to the endosperm.”")), 35, ("orientation",),
        lead="A barley lot is germinating unevenly, and the Head Maltster needs a biochemical diagnosis."),

    "water_profile": Quest("A Tale of Two Ions", "water_chemist",
        "“The pilot pale ale tastes sharp and thin. Build a useful profile from chemistry, not merely a city name,” says the Water Chemist.", (
        T("ph_meter", "Check mash pH.", "“This cooled, representative sample is outside the most useful mash-pH range,” reports the pH Meter. “Remember that my scale is logarithmic: one pH unit represents a tenfold change in hydrogen-ion activity. Before changing salts, ask Bicarbonate why the water resisted the acidifying effect of the grist.”"),
        T("bicarbonate", "Consult Bicarbonate.", "“I accept added protons and contribute to alkalinity—the water's resistance to a decrease in pH,” says Bicarbonate. “Do not confuse that buffering capacity with hardness, which mainly reflects polyvalent ions. Ask Calcium how an ion associated with hardness can nevertheless help the mash.”"),
        T("calcium_ion", "Ask Calcium about mash effects.", "“I can promote phosphate reactions that lower mash pH and can stabilize alpha-amylase against thermal inactivation,” says Calcium. “I also support yeast and flocculation later. Once alkalinity is corrected, consult Sulfate before deciding how the flavor ions should be balanced.”"),
        T("sulfate_ion", "Ask Sulfate about flavor.", "“I often sharpen the impression of bitterness and dryness, but too much of me can make the finish seem harsh,” says Sulfate. “That could contribute to this pale ale's complaint, but I am only half of the flavor balance. Compare my effect with Chloride before recommending a profile.”"),
        T("chloride_ion", "Ask Chloride about flavor.", "“I tend to emphasize fullness and apparent sweetness, countering the thin impression that excessive sulfate can create,” says Chloride. “Neither ion repairs an unsuitable mash pH by itself. Return to the Water Chemist with separate recommendations for alkalinity control and flavor balance.”"),
        T("water_chemist", "Return with a balanced recommendation.", "“Exactly: first correct the bicarbonate-driven alkalinity so the grist can establish a useful mash pH, then set sulfate and chloride deliberately for the intended sensory balance,” says the Water Chemist. “A city name or a hard-versus-soft label cannot replace that chemistry. Next, the Carbohydrate Curator needs help inside the Mash Tun.”")), 35, ("malt_house",),
        lead="A pilot pale ale tastes sharp and thin, and the Water Chemist needs help correcting its chemistry."),

    "starch_structure": Quest("Rebuild the Carbohydrate Map", "carbohydrate_curator",
        "The Carbohydrate Curator gestures toward a scrambled set of molecular labels. “Before you diagnose a mash, prove that you can distinguish its substrate, products, and structural look-alikes. Rebuild this map from monomer to hydrated starch.”", (
        T("glucose", "Identify the monomer used to build barley starch.", "“I am glucose, a single sugar unit. Thousands or millions of copies of me can be linked into polysaccharides with very different properties,” says Glucose."),
        T("maltose", "Identify the brewing disaccharide released from starch.", "“I am maltose: two glucose units joined alpha-1,4. Beta-amylase releases me repeatedly from nonreducing starch-chain ends,” says Maltose."),
        T("sucrose", "Determine which monosaccharides make sucrose.", "“I am a disaccharide of glucose and fructose,” says Sucrose. “The number of sugar units alone does not identify a molecule.”"),
        T("lactose", "Compare lactose with sucrose.", "“I contain galactose and glucose, not fructose and glucose,” says Lactose. “I am useful here as a comparison, not as the principal sugar extracted from malt.”"),
        T("amylose", "Trace the structure and packing of amylose.", "“I am mostly an unbranched alpha-1,4 glucose chain. I can form a left-handed helix and pack into hydrogen-bonded regions that exclude water,” says Amylose."),
        T("amylopectin", "Trace amylopectin and locate its branch points.", "“I supply roughly seventy to eighty percent of ordinary starch. Alpha-1,6 branch points interrupt my alpha-1,4 chains every few dozen glucose units,” says Amylopectin."),
        T("glycogen", "Compare glycogen with amylopectin.", "“Animals store glucose in my chains. I resemble amylopectin but branch more frequently, supporting rapid glucose mobilization,” says Glycogen."),
        T("cellulose", "Explain why cellulose behaves unlike starch.", "“My glucose units use beta-1,4 linkages, producing straight structural chains rather than the alpha-linked substrate recognized by starch-degrading amylases,” says Cellulose."),
        T("crystallinity_analyst", "Ask why packed starch can resist amylases.", "“Aligned, hydrogen-bonded chains exclude water and form ordered regions. Enzymes cannot efficiently attack bonds they cannot physically reach,” says the Crystallinity Analyst."),
        T("gelatinization_specialist", "Determine what gelatinization changes.", "“Heat and water disrupt ordered packing and hydrate the glucan chains. That improves enzyme access, but gelatinization itself does not hydrolyze starch into sugar,” says the Gelatinization Specialist."),
        T("grain_stress_agronomist", "Ask how growing conditions can change gelatinization.", "“Heat and drought during grain filling can raise starch gelatinization temperature. If access requires temperatures that damage the malt's amylases, self-conversion becomes difficult,” says the Grain-Stress Agronomist."),
        T("carbohydrate_curator", "Return to the Carbohydrate Curator and rebuild the map.", "“Correct: composition identifies the building blocks, linkage and branching determine architecture, and heat plus water determine accessibility. Before diagnosing the production mash, visit the Protein Chemist through the Protein Rest. A heat-treated enzyme panel needs investigation,” says the Carbohydrate Curator.")), 45, ("water_profile",),
        lead="A scrambled molecular map must be rebuilt before the production mash can be diagnosed."),

    "protein_enzymes": Quest("The Enzyme That Lost Its Shape", "protein_chemist",
        "The Protein Chemist holds up two assay trays. “The proteins are still present after a heat pulse, but several activities vanished. Trace protein structure into enzyme function, identify which members of the mash enzyme crew failed, and help me interpret the iodine-dark sample.”", (
        T("amino_acid_guide", "Identify the common building blocks of proteins.", "“Proteins are linear heteropolymers assembled from twenty standard amino acids. Their shared backbone permits chain formation, while different side chains give the residues different chemical behavior,” says the Amino Acid Guide."),
        T("peptide_bond", "Determine what joins amino acids into a protein backbone.", "“Peptide bonds covalently join amino acids. Proteases hydrolyze those bonds; ordinary heat denaturation disrupts higher-order structure without normally cutting the primary backbone,” says Peptide Bond."),
        T("protein_architect", "Trace the four levels of protein structure.", "“Primary structure is sequence; secondary structure includes local helices and sheets; tertiary structure is the overall fold of one chain; quaternary structure describes associations among multiple chains,” says the Protein Architect."),
        T("molecular_chaperone", "Ask how proteins reach a useful fold without aggregating.", "“Hydrophobic groups tend to become buried during folding. I shelter exposed hydrophobic surfaces and reduce aggregation, but the amino-acid sequence still contains the folding information,” says the Molecular Chaperone."),
        T("denatured_protein", "Examine what the heat pulse changed.", "“My peptide backbone remains, but the higher-order fold and activity were lost. Exposed hydrophobic regions also made damaged molecules aggregate,” reports the Denatured Protein."),
        T("enzyme_catalyst", "Ask what an enzyme changes in a reaction.", "“I lower the activation-energy barrier by providing a favorable reaction pathway. I accelerate approach to equilibrium; I do not change the reaction's equilibrium or overall free-energy difference,” says the Enzyme Catalyst."),
        T("active_site", "Examine how an active site produces selectivity and catalysis.", "“Only a small fraction of residues may bind, orient, strain, or chemically assist the substrate. Selectivity means preferring some substrates; specificity is the limiting case of acting on essentially one,” says the Active Site."),
        T("condition_controller", "Compare the useful temperature ranges of the mash enzymes.", "“Different enzymes have different working windows: beta-glucanase about 98–113°F, many proteases 115–135°F, beta-amylase 130–150°F, and alpha-amylase 155–167°F. A single temperature cannot maximize them all,” says the Enzyme-Condition Controller."),
        T("amylase_mechanist", "Compare alpha-amylase with beta-amylase.", "“Alpha-amylase attacks internal alpha-1,4 bonds, liquefying starch and making dextrins and new ends. Beta-amylase works from nonreducing ends, releasing maltose during saccharification, but is less heat-stable,” says the Amylase Mechanist."),
        T("alpha_amylase", "Ask Alpha-Amylase how internal cleavage changes a mash.", "“Internal cleavage rapidly lowers chain length and viscosity and creates additional ends, but leaves a mixture of dextrins rather than producing only maltose,” says Alpha-Amylase."),
        T("beta_amylase", "Ask Beta-Amylase how maltose is released.", "“I repeatedly remove maltose from accessible nonreducing chain ends. Excessive heat costs my activity and usually shifts the wort toward lower fermentability and greater body,” says Beta-Amylase."),
        T("mash_thickness_technician", "Determine how mash thickness can alter enzyme performance.", "“A very thick mash lets maltose accumulate and inhibit beta-amylase. An excessively thin mash dilutes protective barley phosphate; calcium and ionic conditions also affect enzyme stability,” says the Mash-Thickness Technician."),
        T("beta_glucanase", "Ask Beta-Glucanase why a low-temperature rest may aid runoff.", "“Near 98–113°F I hydrolyze gummy cell-wall beta-glucans. Malting removes most of them, but a stubborn remainder can raise viscosity and obstruct lautering,” says Beta-Glucanase."),
        T("protease", "Ask Protease what a protein rest changes.", "“I hydrolyze selected peptide bonds, affecting free amino nitrogen, haze, and foam-active proteins. That is chemical cleavage—not merely unfolding a protein with heat,” says Protease."),
        T("glucoamylase", "Ask Glucoamylase how its products differ from maltose-rich wort.", "“I can hydrolyze alpha-1,4 and alpha-1,6 linkages toward glucose. Added glucoamylase can drive very high attenuation and a drier beer than ordinary malt amylases alone,” says Glucoamylase."),
        T("iodine_analyst", "Interpret the iodine-dark assay.", "“Triiodide fits within long amylose helices to form the blue-black complex. Persistent dark color means substantial long starch chains remain; disappearance of color tracks their breakdown but does not identify every sugar product,” says the Iodine-Test Analyst."),
        T("protein_chemist", "Return to the Protein Chemist with the diagnosis.", "“Exactly. The proteins did not disappear—their higher-order structures and active sites were heat-damaged. The surviving alpha-amylase shortened some chains, but lost beta-amylase activity limited maltose production. You are ready to diagnose the production mash,” says the Protein Chemist.")), 55, ("starch_structure",),
        lead="A heat pulse left proteins present but silenced several enzyme activities, and the Protein Chemist needs the damage traced."),

    "stalled_mash": Quest("The Stalled Mash", "head_brewer",
        "An iodine-dark sample worries the Head Brewer. “Decide whether access, temperature, pH, or enzyme activity is responsible.”", (
        T("miller", "Find the Miller and ask whether milling exposed the endosperm.", "“The rollers opened the endosperm, so water and enzymes can reach its starch, but I retained broad husk pieces for the later filter bed,” says the Miller. “The crush is not the bottleneck. Check Gelatinized Starch next to determine whether heat and water disrupted the granules' ordered structure.”"),
        T("gelatinized_starch", "Check starch accessibility.", "“I am swollen and hydrated, and my formerly ordered, hydrogen-bonded regions have opened to enzyme access,” says Gelatinized Starch. “Gelatinization made the glucan chains accessible, but did not hydrolyze them. The dark iodine result must lie downstream, so ask Beta-Amylase whether the temperature history preserved maltose production.”"),
        T("beta_amylase", "Consult Beta-Amylase.", "“I normally remove maltose repeatedly from accessible nonreducing chain ends, but the recorded dough-in temperature exceeded my comfortable range,” says Beta-Amylase. “My loss would reduce fermentability even if another amylase continued shortening chains. Ask the more heat-stable Alpha-Amylase what activity remained.”"),
        T("alpha_amylase", "Consult Alpha-Amylase.", "“I survived well enough to cleave internal alpha-1,4 bonds, lower viscosity, and create shorter dextrins plus new chain ends,” says Alpha-Amylase. “That does not replace Beta-Amylase's sustained maltose production. Verify mash pH before assigning the failure entirely to the hot dough-in.”"),
        T("ph_meter", "Verify mash pH.", "“The representative, cooled sample falls within the intended enzyme range,” reports the pH Meter. “That removes pH as the leading explanation for the lost activity. Return to the Head Brewer and combine the accessible starch, surviving Alpha-Amylase, and heat-damaged Beta-Amylase into one diagnosis.”"),
        T("head_brewer", "Return with the diagnosis.", "“The evidence fits,” says the Head Brewer. “Milling and gelatinization provided access, and pH was acceptable, but the hot dough-in selectively damaged the less heat-stable Beta-Amylase. Alpha-Amylase still produced shorter dextrins, yet maltose production fell; this wort should ferment less completely and leave a fuller-bodied beer.”")), 40, ("protein_enzymes",),
        lead="An iodine-dark mash is not converting as expected, and the Head Brewer needs the cause identified."),

    "clear_wort": Quest("The Stuck Runoff", "lauter_operator",
        "“The grant slowed to a trickle. Find out whether the bed needs patience, recirculation, or gentler sparging,” says the Lauter Operator.", (
        T("husk_keeper", "Examine the husk-supported bed.", "“Intact husk pieces create permeable channels and make the spent grain its own filter,” says the Husk Keeper. “This bed also contains excess flour and compressed patches, so forcing the runoff faster would make the obstruction worse. Ask the Vorlauf Guide whether the cloudy first runnings were handled gently enough for the filter to establish itself.”"),
        T("vorlauf_guide", "Ask about recirculation.", "“Vorlauf returns cloudy first wort above the bed until suspended particles are captured and clarity improves,” says the Vorlauf Guide. “It conditions the filter; it cannot rescue a bed continually pulled tight by aggressive flow. Check the Sparge Technician's rate and distribution across the grain surface.”"),
        T("sparge_technician", "Check sparge flow.", "“I opened the runoff too quickly and distributed the sparge unevenly,” admits the Sparge Technician. “The pressure compacted fine material while channels bypassed other regions. Escort me to the Lauter Operator; we need to reduce the draw and spread the rinse gently rather than force liquid through the bed.”"),
        E("sparge_technician", "lauter_operator", "Escort the Sparge Technician to the operator.", "The Sparge Technician and Lauter Operator reduce the draw and redistribute the rinse. “Flow is returning without tearing channels through the bed,” says the operator. “The intact husks can now support filtration, vorlauf can polish the wort, and controlled sparging can recover extract without compaction or needless husk extraction.”", "“I have the flow record and a gentler distribution plan,” says the Sparge Technician. “Take me to the Lauter Operator so we can reduce the pressure together. Changing the spray without coordinating the runoff would leave the same compaction force across the grain bed.”")), 30, ("stalled_mash",),
        lead="The lauter runoff has slowed to a trickle, and the Lauter Operator needs the obstruction diagnosed."),

    "hop_timing": Quest("The Vanishing Hop Aroma", "kettle_brewer",
        "“The recipe has plenty of hops but almost no aroma. Follow the molecules through heat and time,” says the Kettle Brewer.", (
        T("humulone", "Ask Humulone what boiling does.", "“I begin as a poorly soluble hop alpha acid,” says Humulone. “Kettle heat rearranges me into a more soluble iso-alpha acid that contributes characteristic bitterness. Ask the Isomerization Chemist why the duration of hot contact makes an early addition behave differently from a late one.”"),
        T("isomerization_chemist", "Ask why early additions favor bitterness.", "“Longer boiling provides more time for alpha-acid isomerization and extraction, so an early addition is used efficiently for bitterness,” says the Isomerization Chemist. “But heat and escaping steam also remove volatile molecules. Find Myrcene in the Hop Oil Laboratory and ask what prolonged boiling did to the missing aroma.”"),
        T("myrcene", "Ask Myrcene why aroma disappears.", "“I am one of the volatile components associated with hop aroma,” says Myrcene. “A vigorous boil carries much of me away with the vapor, so a recipe can contain abundant hops yet retain little aroma after long hot contact. Ask the Dry Hopper how timing can preserve volatile character.”"),
        T("dry_hopper", "Ask how to retain aroma.", "“Late-kettle additions shorten the period of volatilization, while dry hopping extracts aroma on the cool side without a long boil,” says the Dry Hopper. “Those approaches do not serve exactly the same purpose as an early bittering charge. Return to the Kettle Brewer with a schedule that separates bitterness, flavor, and aroma.”"),
        T("kettle_brewer", "Return with a revised schedule.", "“That explains the vanished aroma,” says the Kettle Brewer. “We asked every hop addition to endure the full boil: alpha acids isomerized, but volatile oils escaped. The revised schedule keeps an early charge for bitterness, later additions for flavor, and late or cold-side additions for aroma retention.”")), 35, ("clear_wort",),
        lead="A heavily hopped batch has almost no hop aroma, and the Kettle Brewer needs to know where it went."),

    "fermentation": Quest("Save the Stalled Fermentation", "cellar_manager",
        "“Gravity stopped falling. Diagnose the wort and cells before anyone dumps oxygen into finished beer,” says the Cellar Manager.", (
        T("qa_technician", "Verify gravity and sampling.", "“I repeated the gravity measurement with a calibrated instrument and a representative, degassed sample,” says the QA Technician. “Residual extract is genuinely present, so this is not a transcription or sampling illusion. Ask the Yeast Culturist whether enough healthy cells were pitched and whether they had the reserves needed to grow.”"),
        T("yeast_culturist", "Check viability and pitch history.", "“The pitch contained too few vigorous cells, and their membrane reserves were depleted,” says the Yeast Culturist. “They handled the easiest sugars but struggled as the wort composition changed. Inspect Maltose Permease next, because residual maltose cannot be fermented until the cells transport it across the membrane.”"),
        T("maltose_permease", "Inspect maltose uptake.", "“I use the proton gradient to bring maltose into the cell; the sugar does not simply diffuse through the lipid bilayer,” says Maltose Permease. “Glucose repression delayed production of the maltose-use machinery, and these stressed cells never recovered sufficient capacity. Ask Maltase what must happen after maltose reaches the cytoplasm.”"),
        T("maltase", "Ask how intracellular maltose is used.", "“Once transport delivers maltose, I hydrolyze its alpha-1,4 bond to make two glucose molecules,” says Maltase. “Those glucose units can then enter central metabolism. Uptake and hydrolysis both depend on viable cells, so ask the Lipid Specialist why oxygen before fermentation—but not oxygen added carelessly now—matters to yeast recovery.”"),
        T("lipid_specialist", "Ask why early wort oxygen matters.", "“Yeast use oxygen early to synthesize sterols and unsaturated fatty acids needed for functional membranes and growth,” says the Lipid Specialist. “After fermentation is underway, oxygen instead promotes beer staling. Bring the Yeast Culturist to the Cellar Manager so they can plan an active-cell recovery without aerating finished beer.”"),
        E("yeast_culturist", "cellar_manager", "Escort the Yeast Culturist to the Cellar Manager.", "The Yeast Culturist presents an active culture and a controlled recovery plan. “We will restore adequate viable biomass and monitor gravity rather than dump oxygen into the beer,” says the Cellar Manager. “Maltose transport and metabolism can resume while we avoid the oxidative damage that late aeration would cause.”", "“I have prepared an active culture with verified viability and adequate membrane reserves,” says the Yeast Culturist. “Escort me to the Cellar Manager. We should restore cell capacity and monitor gravity without introducing the late oxygen that would promote staling.”")), 45, ("hop_timing",),
        lead="A fermentation has stopped with residual extract remaining, and the Cellar Manager needs a recovery plan."),

    "diacetyl": Quest("Butter in the Cellar", "sensory_analyst",
        "The Sensory Analyst detects butter and butterscotch. “Trace the compound to its precursor and choose a biochemical remedy.”", (
        T("diacetyl_molecule", "Question Diacetyl.", "“Humans detect me at a low concentration as butter or butterscotch,” says Diacetyl. “Finding me identifies the immediate flavor-active compound, but not where I came from or whether yeast can remove me. Locate Alpha-Acetolactate to trace the precursor that escaped from yeast metabolism.”"),
        T("alpha_acetolactate", "Find alpha-acetolactate.", "“Yeast form me during branched-chain amino-acid biosynthesis, and some of me can leave the cell,” says Alpha-Acetolactate. “Outside the cell I can convert into flavor-active diacetyl. Ask the Maturation Operator how warm, active yeast can complete the cleanup before the beer is chilled.”"),
        T("maturation_operator", "Ask about a diacetyl rest.", "“A warm rest keeps yeast metabolically active so they can take up diacetyl and reduce it to less flavor-active products,” says the Maturation Operator. “Cooling too early would slow that cleanup. Escort me to the Sensory Analyst so we can schedule the rest and define when repeated tasting permits cooling.”"),
        E("maturation_operator", "sensory_analyst", "Escort the operator to the Sensory Analyst.", "The Maturation Operator schedules a warm rest while the Sensory Analyst prepares blinded follow-up samples. “We will not cool by the calendar alone,” says the analyst. “We will confirm that active yeast reduced the buttery diacetyl before lowering the temperature for maturation.”", "“I have the temperature schedule and yeast-activity record,” says the Maturation Operator. “Escort me to the Sensory Analyst so analytical timing and blinded tasting can be coordinated. The beer should remain warm until active yeast have reduced the diacetyl burden.”")), 32, ("fermentation",),
        lead="A cellar sample tastes strongly of butter and butterscotch, and the Sensory Analyst needs its biochemical source traced."),

    "sulfur": Quest("The Sulfur Alarm", "sulfur_engineer",
        "“One sample smells like eggs; another like cooked vegetables. Separate their origins,” says the Sulfur Engineer.", (
        T("hydrogen_sulfide", "Identify the rotten-egg compound.", "“My rotten-egg aroma points toward hydrogen sulfide produced through yeast sulfur metabolism,” says Hydrogen Sulfide. “Cell health, nutrients, strain, and fermentation conditions can influence my appearance. Do not assume the cooked-vegetable sample has the same cause; question Dimethyl Sulfide separately.”"),
        T("dms_molecule", "Identify the cooked-vegetable compound.", "“My aroma is often described as cooked corn or vegetables rather than rotten egg,” says Dimethyl Sulfide. “Malt contains S-methylmethionine, a precursor that can generate me during heating. Ask the Boil Engineer why kettle design and vapor escape determine whether I remain in the wort.”"),
        T("boil_engineer", "Ask how boiling affects DMS.", "“A vigorous, uncovered boil allows volatile DMS to leave with the steam,” says the Boil Engineer. “A weak boil, covered kettle, or slow cooling can favor its retention or continued formation. Return to the Sulfur Engineer with separate process explanations for the two sensory samples.”"),
        T("sulfur_engineer", "Return with the diagnosis.", "“Correct: similar category names do not imply a common mechanism,” says the Sulfur Engineer. “The rotten-egg sample implicates yeast-related hydrogen sulfide, while the cooked-vegetable sample implicates malt-precursor and boil-related DMS. We will correct fermentation and kettle practices separately rather than apply one generic sulfur remedy.”")), 30, ("diacetyl",),
        lead="Two samples have different sulfur faults, and the Sulfur Engineer needs their identities and origins separated."),

    "lightstruck": Quest("The Sunlit Six-Pack", "packaging_lead",
        "“A display batch became skunky. Reconstruct the photochemistry and recommend a package,” says the Packaging Lead.", (
        T("light_tester", "Test the beer in the lightstrike booth.", "“The protected control remains normal, but blue-visible and near-ultraviolet exposure rapidly reproduces the skunky fault in this hopped beer,” says the Lightstrike Tester. “That makes light-driven chemistry more likely than a slow microbial change. Ask Riboflavin how absorbed light initiates the reaction.”"),
        T("riboflavin", "Ask Riboflavin about its role.", "“I absorb light and enter an excited state that can participate in radical chemistry involving sulfur and hop-derived compounds,” says Riboflavin. “I begin the photochemical chain, but another molecule produces the recognizable odor. Find MBT and ask why even a tiny amount dominates the sample.”"),
        T("mbt_molecule", "Identify the skunky product.", "“I am 3-methyl-2-butene-1-thiol, usually shortened to MBT,” says the molecule. “My sensory threshold is extremely low, so photochemistry need produce very little of me before the beer smells skunky. Ask the Can Specialist which package prevents the initiating light from reaching the beer.”"),
        T("can_specialist", "Ask about package protection.", "“An opaque can blocks the wavelengths that drive lightstrike and can also provide an excellent oxygen barrier when seams and handling are sound,” says the Can Specialist. “Clear and green glass offer much less light protection. Return to the Packaging Lead with both a package recommendation and controls for display exposure.”"),
        T("packaging_lead", "Return with a recommendation.", "“The exposure test, excited Riboflavin, and low-threshold MBT form one consistent explanation,” says the Packaging Lead. “We will move this light-sensitive release to opaque cans and reduce light exposure during handling and display. The correction blocks the initiating energy instead of trying to hide the skunky product afterward.”")), 35, ("styles",),
        lead="A display batch became skunky, and the Packaging Lead needs the photochemistry reconstructed."),

    "foam": Quest("The Headless Pint", "taproom_manager",
        "“This beer pours lively, then collapses. Investigate proteins, gas, and glass,” says the Taproom Manager.", (
        T("ltp1", "Ask LTP1 about foam.", "“Heat-modified forms of me can help stabilize beer foam at the gas–liquid interface,” says LTP1. “Lipids generally work against that stability, so both protein history and contamination matter. Ask Protein Z whether another barley-derived protein supports the bubble films in this batch.”"),
        T("protein_z", "Ask Protein Z about foam.", "“I am also associated with foam stability, although no single protein guarantees a lasting head,” says Protein Z. “The assay shows that useful foam-active protein remains. Check carbonation and serving temperature next, because even a sound protein mixture needs appropriate gas release to build foam.”"),
        T("carbonation_operator", "Check carbonation and serving temperature.", "“The dissolved gas, keg pressure, and beer temperature are appropriate for this service,” says the Carbonation Operator. “Temperature affects gas solubility, and nucleation affects bubble formation, but those measurements do not explain the rapid collapse. Inspect the actual glass surface for lipids or detergent residue.”"),
        T("glass_steward", "Inspect the glassware.", "“A thin grease film survived the cleaning procedure,” says the Glass Steward. “Lipids disrupt the films around bubbles, which explains why a lively pour collapses even though carbonation and foam-active proteins are present. Return to the Taproom Manager after I replace the glass and correct the washing protocol.”"),
        T("taproom_manager", "Return to the Taproom Manager.", "“The beer now forms and retains a proper head in genuinely clean glassware,” says the Taproom Manager. “The comparison mattered: LTP1 and Protein Z were present, carbonation and temperature were suitable, and grease—not the recipe—was the immediate foam-negative factor. We will verify glass cleanliness before changing the beer.”")), 35, ("lightstruck",),
        lead="A lively pint rapidly loses its foam, and the Taproom Manager needs to know why."),

    "styles": Quest("Two Yeasts, Two Cellars", "style_judge",
        "“Use physiology and process—not stereotypes—to identify these ale and lager paths,” says the Style Judge.", (
        T("ale_yeast", "Interview the warm-fermenting yeast.", "“I am Saccharomyces cerevisiae, the species most commonly associated with ale fermentation,” says Ale Yeast. “Warmer fermentation can make some strains express prominent esters, but strain and process both matter. Interview Lager Yeast rather than assuming temperature alone identifies the other cellar path.”"),
        T("lager_yeast", "Interview the cool-fermenting yeast.", "“I am Saccharomyces pastorianus, a hybrid yeast adapted to cool lager fermentation,” says Lager Yeast. “My physiology and the cellar schedule distinguish this path, but neither all lagers nor all ales taste alike. Ask the Ester Chemist which interacting variables shape fruity fermentation products.”"),
        T("ester_chemist", "Ask what controls esters.", "“Ester production depends on yeast strain, temperature, oxygenation, pitch rate, growth, and wort composition,” says the Ester Chemist. “A warm fermentation may encourage some ester profiles, but it is not an isolated on–off switch. Ask the Cold Keeper what lagering contributes after primary fermentation.”"),
        T("cold_keeper", "Ask what lagering accomplishes.", "“Cold maturation encourages settling and clarification while time permits flavor changes and cleanup,” says the Cold Keeper. “It follows fermentation; it does not define the yeast by itself or erase every earlier process choice. Return to the Style Judge with a physiological and process-based comparison of the two paths.”"),
        T("style_judge", "Return with the identification.", "“Your identification rests on yeast biology and the complete process rather than stereotypes,” says the Style Judge. “S. cerevisiae commonly follows the warmer ale path, while hybrid S. pastorianus is adapted to cooler lager fermentation and cold maturation. Strain and operating choices still create substantial diversity within both families.”")), 35, ("sulfur",),
        lead="Two unidentified cellar paths must be distinguished using yeast physiology and process evidence."),

    "sanitation": Quest("The Uninvited Fermenter", "microbiologist",
        "“A package is overcarbonated and unexpectedly sour. Trace possible contaminants and their route,” says the Microbiologist.", (
        T("lactic_bacterium", "Assess the lactic bacterium.", "“Some lactic acid bacteria can convert substrate into acids that lower beer pH and create sourness,” says the Lactic Bacterium. “Hop iso-alpha acids inhibit many Gram-positive strains, but resistance and brewery conditions vary. The excess package pressure also demands a carbon-dioxide source, so assess Wild Yeast's access to residual carbohydrate.”"),
        T("wild_yeast", "Assess the wild yeast.", "“I can consume carbohydrates that the production strain left behind and continue producing carbon dioxide after packaging,” says Wild Yeast. “That explains increasing pressure, while the bacterial isolate can explain acidity. Audit the sanitation records to find a route that could have introduced or protected both contaminants.”"),
        T("sanitation_lead", "Audit cleaning records.", "“This transfer fitting retained organic soil before sanitizer was applied,” says the Sanitation Lead. “Sanitizer cannot reliably reach organisms protected beneath residue. Cleaning must remove the soil first; sanitizing then reduces the remaining microbial population. Escort me to the Microbiologist so we can quarantine the lot and document the corrective action.”"),
        E("sanitation_lead", "microbiologist", "Escort the Sanitation Lead to the lab.", "The Sanitation Lead identifies the contaminated fitting while the Microbiologist separates the isolates. “We will quarantine the package lot, dismantle and clean the fitting, then sanitize and verify it,” says the Microbiologist. “Cleaning removes soil; sanitizing reduces microorganisms. Treating those words as synonyms allowed this protected niche to survive.”", "“I have isolated the suspect fitting and its cleaning record,” says the Sanitation Lead. “Escort me to the Microbiologist so the physical harborage point can be compared with the recovered organisms. That link will support quarantine and a verified clean-then-sanitize correction.”")), 38, ("foam",),
        lead="A package is unexpectedly sour and overcarbonated, suggesting that an uninvited fermenter got inside."),

    "mystery_batch": Quest("The Batch That Does Not Add Up", "qa_chemist",
        "“The production sheet and finished beer disagree. Recheck the batch across departments and build an evidence-based diagnosis,” says the QA Chemist.", (
        T("ph_meter", "Verify the recorded mash pH.", "“A fresh calibrated measurement agrees with the archived mash-pH value,” reports the pH Meter. “The sample handling and logarithmic reading are sound, so pH does not explain the disagreement. Preserve that valid result and ask the QA Technician to independently verify the original- and final-gravity records.”"),
        T("qa_technician", "Verify original and final gravity readings.", "“The instrument records reveal a transcription error: two digits were swapped when original gravity was entered on the production sheet,” says the QA Technician. “That false starting value distorted the calculated attenuation. Continue the audit rather than stopping at the first error; ask the IBU Chemist whether the bitterness number is internally consistent.”"),
        T("ibu_chemist", "Check the bitterness assay.", "“The absorbance-based IBU estimate is analytically consistent when I repeat the extraction and measurement,” says the IBU Chemist. “IBU is an operational chemical estimate, however, and is not identical to perceived bitterness. Check package temperature and carbon-dioxide pressure before comparing all corrected measurements with sensory results.”"),
        T("carbonation_operator", "Check package temperature and CO2 pressure.", "“The beer warmed during the original measurement, which lowered carbon-dioxide solubility and made the dissolved level appear unexpectedly low for the applied pressure,” says the Carbonation Operator. “At a controlled colder temperature the pressure–solubility relationship makes sense. Ask the Sensory Analyst whether a blinded sample now agrees with the corrected record.”"),
        T("sensory_analyst", "Compare the corrected records with a blind sample.", "“The blinded sensory profile agrees with the corrected gravity, bitterness, and carbonation evidence,” says the Sensory Analyst. “That convergence is stronger than forcing the beer to match one faulty entry. Return to the QA Chemist with the valid mash pH, transposed gravity digits, confirmed IBU estimate, and temperature-corrected carbonation result.”"),
        T("qa_chemist", "Return to the QA Chemist with the complete diagnosis.", "“Good,” says the QA Chemist. “No single measurement tells the whole story. Calibrated repeats preserved the valid mash-pH and bitterness results, traceable raw data exposed the gravity transcription error, and temperature control explained carbonation. Independent checks prevented us from making needless process changes to correct beer that existed only on a faulty record.”")), 40, ("sanitation",),
        lead="The production record and finished beer disagree, and the QA Chemist needs an independent investigation."),
}

GIVER_QUESTS = {q.giver: key for key, q in QUESTS.items()}
