from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Quiz:
    prompt: str
    options: tuple[str, ...]
    correct: int
    feedback: tuple[str, ...]
    explanation: str
    arrival_exclusions: tuple[str, ...] = ()


def Q(prompt, options, correct, explanation, exclusions=()):
    feedback = tuple("Review the underlying process relationship, not just the vocabulary." if i != correct else "" for i in range(4))
    return Quiz(prompt, options, correct, feedback, explanation, exclusions)


QUIZZES = {
 "germination_floor": Q("Which signal stimulates the barley aleurone to produce hydrolytic enzymes during germination?", ("Insulin", "Gibberellic acid", "Lactic acid", "Humulone"), 1, "Gibberellic acid from the embryo signals the aleurone to synthesize enzymes including alpha-amylase and proteases.", ("aleurone",)),
 "kiln": Q("What is a central tradeoff when malt is kilned more intensely?", ("More flavor/color but less surviving enzyme activity", "More oxygen but no drying", "More starch synthesis", "Complete removal of protein"), 0, "Hotter or longer kilning develops color and flavor while destroying a greater fraction of heat-sensitive enzyme activity."),
 "ion_gallery": Q("How does alkalinity differ from hardness?", ("They are always identical", "Alkalinity resists pH decrease; hardness mainly reflects polyvalent ions", "Hardness measures ethanol", "Alkalinity measures hop oil"), 1, "Alkalinity is acid-neutralizing capacity, often involving bicarbonate; hardness chiefly reflects ions such as calcium and magnesium.", ("ph_bench",)),
 "mash_tun": Q("A brewer wants a more fermentable wort. Which mash emphasis generally favors that goal?", ("A lower-temperature beta-amylase-favoring rest", "Maximum caramelization", "A covered wort boil", "Late oxygen exposure"), 0, "A lower saccharification rest preserves more beta-amylase activity and tends to yield more maltose and greater fermentability.", ("beta_rest",)),
 "carbohydrate_lab": Q("Which description correctly distinguishes a monosaccharide from a disaccharide?", ("One sugar unit versus two linked sugar units", "A straight polymer versus a branched polymer", "A plant molecule versus an animal molecule", "A sweet molecule versus a nonsweet molecule"), 0, "A monosaccharide is one sugar unit; a disaccharide contains two monosaccharide units joined by a glycosidic bond.", ("glucose_bench", "disaccharide_gallery")),
 "glucose_bench": Q("What role does glucose play in barley starch?", ("It is the repeating monosaccharide building block", "It creates peptide bonds", "It is the alpha-amylase enzyme", "It is found only at branch points"), 0, "Both amylose and amylopectin are polymers built from glucose units, even though their chain architectures differ.", ("amylose_helix", "amylopectin_arbor")),
 "disaccharide_gallery": Q("Which list correctly identifies three disaccharides by their component monosaccharides?", ("Maltose: glucose + glucose; sucrose: glucose + fructose; lactose: galactose + glucose", "Maltose: fructose + galactose; sucrose: two glucose; lactose: two fructose", "Maltose: glucose + fructose; sucrose: galactose + glucose; lactose: two glucose", "All three contain the same pair of monosaccharides"), 0, "Maltose contains two glucose units, sucrose contains glucose and fructose, and lactose contains galactose and glucose.", ("glucose_bench",)),
 "polymer_comparison": Q("Which comparison among glucose polymers is accurate?", ("Glycogen is more highly branched than amylopectin", "Cellulose has the same alpha-1,4 geometry as amylose", "Amylose is more branched than glycogen", "All glucose polymers have identical physical properties"), 0, "Glycogen resembles amylopectin but is more frequently branched, which supports rapid mobilization of animal glucose stores.", ("amylopectin_arbor",)),
 "gelatinization_chamber": Q("What does starch gelatinization accomplish during mashing?", ("Heat and water disrupt ordered packing and improve enzyme access", "Heat directly hydrolyzes all starch into glucose", "Cooling creates alpha-1,6 branch points", "Water converts cellulose into amylopectin"), 0, "Gelatinization hydrates starch and disrupts ordered granule structure; it enables amylase access but is not itself enzymatic hydrolysis.", ("crystallinity_lab",)),
 "crystallinity_lab": Q("Why can crystalline regions of starch resist amylase attack?", ("Tightly hydrogen-bonded chains exclude water and limit physical access", "They contain no glycosidic bonds", "They are made entirely of protein", "They permanently destroy water molecules"), 0, "Aligned starch chains can hydrogen-bond into ordered regions that exclude water and physically restrict amylase access.", ("gelatinization_chamber",)),
 "amylose_helix": Q("Which description best fits amylose?", ("A mostly unbranched alpha-1,4 glucose polymer that can form a left-handed helix", "A glucose-fructose disaccharide", "A beta-1,4 structural polymer", "A highly branched animal glucose store"), 0, "Amylose is a mostly unbranched alpha-1,4 glucan whose chains can adopt left-handed helices and participate in crystalline packing.", ("amylopectin_arbor",)),
 "amylopectin_arbor": Q("How does amylopectin differ structurally from amylose?", ("It contains alpha-1,6 branch points within an alpha-1,4 glucose polymer", "It is made from galactose instead of glucose", "It contains only beta-1,4 linkages", "It is a two-sugar molecule"), 0, "Amylopectin has alpha-1,4-linked chains joined at alpha-1,6 branch points and normally makes up most starch.", ("amylose_helix",)),
 "amino_acid_gallery": Q("Which statement best describes the relationship between amino acids and proteins?", ("Every protein contains only one kind of amino acid", "Proteins are linear heteropolymers assembled from twenty standard amino acids", "Amino acids are produced by starch gelatinization", "A protein's side chains are all chemically identical"), 1, "Proteins are linear heteropolymers: their backbones are assembled from the same set of twenty standard amino acids, whose varied side chains contribute different chemical properties.", ("peptide_bond_bench",)),
 "peptide_bond_bench": Q("Which change directly breaks a protein's primary-structure backbone?", ("Formation of an alpha helix", "Burial of hydrophobic side chains", "Hydrolysis of peptide bonds", "Reversible substrate binding"), 2, "Peptide-bond hydrolysis breaks the covalent backbone and changes primary structure. Denaturation usually disrupts higher-order structure without hydrolyzing that backbone.", ("denaturation_bay",)),
 "protein_structure_gallery": Q("Which pairing of a protein structural level with its meaning is correct?", ("Primary—amino-acid sequence", "Secondary—association of several separate subunits", "Tertiary—only alpha helices and beta sheets", "Quaternary—the order of residues in one chain"), 0, "Primary structure is amino-acid sequence; secondary structure includes local helices and sheets; tertiary structure is the overall fold of one chain; quaternary structure describes associations among multiple chains.", ("folding_chamber",)),
 "folding_chamber": Q("How can a molecular chaperone help a newly made protein?", ("By changing its amino-acid sequence", "By sheltering exposed hydrophobic surfaces and limiting aggregation during folding", "By converting every peptide bond into a glycosidic bond", "By permanently fixing any possible folded shape"), 1, "Chaperones provide protected folding environments and reduce inappropriate contacts among exposed hydrophobic surfaces; they do not rewrite the protein's sequence.", ("denaturation_bay",)),
 "denaturation_bay": Q("A heated enzyme remains chemically detectable but loses activity and forms aggregates. What is the best explanation?", ("Its amino acids became glucose", "Its equilibrium constant became zero", "Its higher-order fold was disrupted and exposed hydrophobic surfaces associated", "Every peptide bond was hydrolyzed"), 2, "Heat can disrupt secondary, tertiary, or quaternary structure, deforming the active site. Newly exposed hydrophobic surfaces can then promote aggregation even though the primary backbone remains largely intact.", ("folding_chamber", "enzyme_catalysis_lab")),
 "enzyme_catalysis_lab": Q("What does an enzyme change about a chemical reaction?", ("It lowers the activation-energy barrier without changing the reaction equilibrium", "It makes an unfavorable equilibrium favorable", "It changes the net free-energy difference between reactants and products", "It is permanently consumed as a reactant"), 0, "An enzyme provides a lower-activation-energy pathway and speeds approach to equilibrium in both directions; it does not change the equilibrium position or overall free-energy difference.", ("active_site_workshop",)),
 "active_site_workshop": Q("Why can a small active site determine an enzyme's selectivity?", ("Every residue in the protein contacts every substrate atom", "A few positioned residues can recognize, orient, strain, and chemically assist particular substrates", "Selectivity depends only on the enzyme's color", "The active site changes the reaction equilibrium"), 1, "A relatively small set of active-site residues can make complementary contacts and position catalytic groups. Selectivity is preference among substrates; specificity is the limiting case of acting on essentially one.", ("enzyme_catalysis_lab",)),
 "enzyme_conditions_lab": Q("Which sequence orders these brewing-enzyme temperature windows from lowest to highest?", ("Alpha-amylase, beta-amylase, proteases, beta-glucanase", "Beta-amylase, beta-glucanase, alpha-amylase, proteases", "Beta-glucanase, proteases, beta-amylase, alpha-amylase", "Proteases, alpha-amylase, beta-glucanase, beta-amylase"), 2, "The useful windows rise approximately from beta-glucanase (98–113°F), through many proteases (115–135°F) and beta-amylase (130–150°F), to alpha-amylase (155–167°F).", ("amylase_mechanism_lab",)),
 "amylase_mechanism_lab": Q("Which comparison between the principal malt amylases is accurate?", ("Alpha-amylase releases only glucose; beta-amylase makes branch points", "Alpha-amylase attacks internal alpha-1,4 bonds; beta-amylase releases maltose from nonreducing ends", "Both enzymes hydrolyze peptide bonds", "Beta-amylase is generally more heat-stable than alpha-amylase"), 1, "Alpha-amylase is an endo-acting liquefying enzyme that creates shorter dextrins and new ends. Beta-amylase is an exo-acting saccharifying enzyme that releases maltose from nonreducing ends and is less heat-stable.", ("beta_rest", "alpha_rest")),
 "mash_thickness_station": Q("Why can both an extremely thick mash and an extremely thin mash hinder beta-amylase?", ("A thick mash can accumulate inhibitory maltose, while a thin mash can dilute protective phosphate", "Both conditions convert protein directly into starch", "A thick mash destroys all water, while a thin mash contains no substrate", "Both conditions prevent barley from being milled"), 0, "In a very thick mash, accumulated maltose can inhibit beta-amylase. Excess dilution can reduce the protection supplied by barley phosphate; calcium and broader ionic conditions also affect enzyme stability.", ("enzyme_conditions_lab",)),
 "accessory_enzyme_lab": Q("Which assignment of a brewing enzyme to its function is correct?", ("Beta-glucanase—creates gummy cell walls; protease—forms peptide bonds; glucoamylase—makes starch", "Beta-glucanase—reduces beta-glucan viscosity; protease—hydrolyzes peptide bonds; glucoamylase—releases glucose from alpha-1,4 and alpha-1,6 glucans", "All three enzymes release only maltose", "All three enzymes catalyze hop isomerization"), 1, "Beta-glucanase attacks gummy cell-wall glucans, proteases hydrolyze selected peptide bonds, and glucoamylase can attack alpha-1,4 and alpha-1,6 linkages toward glucose.", ("protein_rest",)),
 "iodine_test_alcove": Q("Why does iodine produce a blue-black signal with substantial unconverted starch?", ("Iodine hydrolyzes starch into blue glucose", "Triiodide associates within long amylose helices to form a colored complex", "Amylopectin is a blue protein", "Iodine converts peptide bonds into alpha-1,6 branches"), 1, "Linear triiodide fits within the amylose helix and produces a blue-black complex. Loss of color tracks disappearance of sufficiently long starch chains, but does not identify every sugar product.", ("conversion_bench",)),
 "conversion_bench": Q("Why does starch gelatinization matter during mashing?", ("It makes starch crystalline", "It improves enzyme access to glucan chains", "It makes nitrogen gas", "It is hop isomerization"), 1, "Gelatinization disrupts ordered granules so amylases can reach amylose and amylopectin more effectively.", ("beta_rest","alpha_rest")),
 "lauter_tun": Q("What normally serves as the principal filter medium during lautering?", ("Yeast sediment", "The malt husk grain bed", "Hop oil", "Bottle glass"), 1, "The spent-grain bed, supported by relatively intact husks, filters wort above the false bottom.", ("grain_bed",)),
 "kettle": Q("Which event is promoted by wort boiling?", ("Alpha-acid isomerization", "Maltose transport into yeast", "Barley germination", "Cold settling"), 0, "Kettle heat isomerizes hop alpha acids into more soluble bitter iso-alpha acids.", ("alpha_acid_bench",)),
 "hot_break": Q("What contributes to the hot break?", ("Heat-denatured and aggregated wort proteins", "New barley embryos", "Only dissolved CO2", "Intact yeast chromosomes"), 0, "Boiling denatures proteins and promotes aggregates with polyphenols and other material that form hot break."),
 "oxygenation_station": Q("Why is cooled pitching wort oxygenated?", ("To let yeast synthesize sterols and unsaturated fatty acids", "To isomerize hops", "To carbonate finished beer", "To create starch"), 0, "Early wort oxygen supports membrane-lipid synthesis and growth; oxygen introduced after fermentation promotes staling.", ("lipid_workshop",)),
 "maltose_gate": Q("How does brewing yeast typically bring maltose into the cell?", ("Simple diffusion through lipids", "Proton-linked active transport", "A DNA polymerase", "Endocytosis of starch"), 1, "Maltose permease uses the proton gradient; intracellular maltase then cleaves maltose into two glucose molecules.", ("maltase_bench",)),
 "nad_recycling": Q("Why must alcoholic fermentation regenerate NAD+?", ("So glycolysis can continue oxidizing substrate", "So hops can grow", "So starch can crystallize", "So bottles block light"), 0, "Reduction of acetaldehyde to ethanol reoxidizes NADH to NAD+, sustaining glycolytic flux."),
 "diacetyl_rest": Q("What is the purpose of a diacetyl rest?", ("Encourage active yeast to remove diacetyl", "Isomerize alpha acids", "Germinate barley", "Increase light exposure"), 0, "A warm period with active yeast promotes uptake and reduction of buttery diacetyl to less flavor-active compounds."),
 "sulfur_vent": Q("Which pairing is most accurate?", ("H2S—rotten egg; DMS—cooked corn/vegetable", "H2S—banana; DMS—vanilla", "H2S—bitterness; DMS—foam", "Both are always odorless"), 0, "Hydrogen sulfide is classically rotten-egg-like; dimethyl sulfide often evokes cooked corn or vegetables."),
 "alpha_acid_bench": Q("What happens to humulone during a productive kettle boil?", ("It becomes DNA", "It isomerizes to a more soluble bitter form", "It becomes maltose", "It makes oxygen"), 1, "Heat rearranges hop alpha acids into iso-alpha acids with greater solubility and characteristic bitterness.", ("kettle",)),
 "oil_lab": Q("Why do late hop additions usually retain more aroma than early additions?", ("Hop oils are volatile", "Alpha acids are proteins", "Yeast makes cellulose", "Late hops contain no water"), 0, "Many hop essential-oil components are volatile and are lost during prolonged vigorous boiling.", ("dry_hop_gallery",)),
 "lightstrike_booth": Q("Which package offers the strongest protection against lightstruck flavor?", ("Clear glass", "Green glass", "An opaque can", "An open pitcher"), 2, "An opaque can blocks the wavelengths that drive riboflavin/hop photochemistry and skunky MBT formation.", ("canning_line",)),
 "carbonation_station": Q("At the same applied CO2 pressure, which beer retains more dissolved CO2?", ("The colder beer", "The warmer beer", "They must be identical", "Only nitrogenated beer"), 0, "Carbon dioxide solubility increases as beer temperature decreases at a fixed pressure."),
 "foam_lab": Q("Which is most likely to damage beer foam?", ("A clean nucleation point", "A grease or detergent residue", "Foam-active barley proteins", "Appropriate carbonation"), 1, "Lipids, grease, and detergent residues destabilize bubble films and can rapidly collapse a beer's head."),
 "qa_chemistry": Q("Why should an unexpected brewery measurement be repeated with a calibrated method?", ("To distinguish a real process change from sampling or instrument error", "To make hops less volatile", "To germinate finished beer", "To eliminate all microbes"), 0, "Independent, calibrated measurements and traceable samples prevent bad data from triggering inappropriate process changes."),
}
